[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-indicator"
version = "0.1.0"
description = "Stock indicators and trading simulation"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "yfinance",
    "requests"
]
